// Auto-generated startup data
export interface StartupData {
  id: string;
  name: string;
  description: string;
  url: string;
  linkedin: string;
  mail: string;
  isInHouse: boolean;
  logo: string;
  createdAt: string;
  updatedAt: string;
}

export const STARTUPS_DATA: StartupData[] = [
  {
    id: "0084ec74-546a-4914-8039-d3830766e163yy",
    name: "Juvo",
    description:
      "Juvo are creating a new way to generate text. Their AI-native writing environment facilitates a smarter and more efficient workflow for writing academic text for students ",
    url: "https://www.juvosolutions.co/",
    linkedin: "https://www.linkedin.com/company/juvosolutions/",
    mail: "",
    isInHouse: true,
    logo: "image-juvo-png",
    createdAt: "2024-03-12T19:41:56Z",
    updatedAt: "2025-06-02T13:15:01Z",
  },
  {
    id: "0084ec74-546a-4914-8039-d3830766e163xx",
    name: "Cortex Robotics",
    description:
      "Cortex Robotics develops intelligent pipe-climbing robots to inspect for corrosion under insulation (CUI). This makes industrial inspections safer and more data-driven, reducing human risk and costly downtime while enabling better maintenance decisions. The company was founded at NTNU School of Entrepreneurship by Daniel Skogland, Celine Slåttelia, Ingeborg Bogen, Kristian Romen, and Oscar Lae, and is supported by a strong entrepreneurial ecosystem and an experienced Advisory Board with deep industry and academic expertise.",
    url: "https://www.cortex-robotics.com/",
    linkedin: "https://www.linkedin.com/company/cortex-robotics/",
    mail: "",
    isInHouse: true,
    logo: "image-cortex-png",
    createdAt: "2024-03-12T19:41:56Z",
    updatedAt: "2025-06-02T13:15:01Z",
  },
  {
    id: "0084ec74-546a-4914-8039-d3830766e163yy",
    name: "Bifrozt",
    description:
      "Bifrozt recognizes the critical need to enhance organizational cyber defense capabilities by bridging the gap between automation and human expertise. Through their Incident Preparation Platform, Bifrozt aims to ensure that organizations of all sizes have access to quality incident response plans and procedures. Bifrozt's mission is to secure the digital future by bridging today's cyber challenges with tomorrow's innovations, starting with simplifying incident preparation for organizations worldwide.",
    url: "https://www.bifrozt.com/",
    linkedin: "https://www.linkedin.com/company/bifrozt/",
    mail: "",
    isInHouse: true,
    logo: "image-bifrozt-png",
    createdAt: "2024-03-12T19:41:56Z",
    updatedAt: "2025-06-02T13:15:01Z",
  },
  {
    id: "ab9b7147-c32e-4efd-a40c-14a65ac97284",
    name: "Bedrock",
    description:
      "The vision of Bedrock is to create a platform that enables businesses to easily collect, manage, and own their data. The platform will feature modular solutions tailored to specific business needs. Bedrock is currently developing a solution that streamlines purchasing processes for manufacturing companies with complex supply chain management. This will be the first module integrated into the Bedrock platform.",
    url: "https://www.usebedrock.net/",
    linkedin: "https://www.linkedin.com/company/usebedrock",
    mail: "contact@usebedrock.net",
    isInHouse: true,
    logo: "image-0219c9dcc1aecfb0b6d090f76ac9aee8f8fab372-800x800-png",
    createdAt: "2025-03-20T11:51:37Z",
    updatedAt: "2025-03-20T11:52:38Z",
  },
    {
    id: "0084ec74-546a-4914-8039-d3830766e163yy",
    name: "Naere Medical",
    description:
      "Naere Medical develops wireless ecg-electrodes for premature and sick infants in the nicu. The wired elecrodes used today contribute to reducing several health benefits for this fragile patient group. With wireless sensors we can ensure stronger and faster parent-child-bonding, less distrubed sleeping periods, as well as an enhanced sence of security and less stress for our most vulnerable patients. The company was founded by Hedda Treu Pettersen at NTNU School of Entrepreneurship.",
    url: "https://www.entreprenorskolen.no/students",
    linkedin: "https://www.linkedin.com/company/naere-medical/",
    mail: "",
    isInHouse: true,
    logo: "image-naere-medical-png",
    createdAt: "2024-03-12T19:41:56Z",
    updatedAt: "2025-06-02T13:15:01Z",
  },
  {
    id: "d5fa2d90-16f7-4fe4-82e9-c16a9fd8c2c2",
    name: "Enmo",
    description:
      "Enmo is a software company that develops a smart energy management system (EMS) to optimize the use and storage of energy from solar panels and batteries. Our solution utilizes weather data, electricity prices, and consumption patterns to enhance decision-making processes. We provide software that seamlessly integrates with inverters from various suppliers, thereby standardizing and simplifying communication.",
    url: "https://www.enmo.ai/",
    linkedin: "",
    mail: "johan@enmo.ai",
    isInHouse: true,
    logo: "image-a989d021a110bf67aaf978fe48f2b13b11136644-592x595-png",
    createdAt: "2024-04-08T18:03:43Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "33f859f5-2964-4022-b5a3-4ff13a134176",
    name: "Artigboks",
    description:
      "Artigboks is a startup offering toy and game rental boxes in public parks, making fun activities more accessible for spontaneous gatherings. With options like kubb, soccer, frisbee, and volleyball, Artigboks encourages social interaction, well-being, and community health by providing easy access to games and sports equipment for everyone. Founded by NTNU School of Entrepreneurship students Henrik Talstad, Francin Vincent, and Jonatan Stenslund, Artigboks aims to boost enjoyment and activity in public spaces.",
    url: "https://www.artigboks.no",
    linkedin: "https://www.linkedin.com/company/artigboks",
    mail: "jonatan@artigboks.no",
    isInHouse: true,
    logo: "image-9ad2ab76eab111879b3df02477ebcc2ad3401906-1024x1024-png",
    createdAt: "2024-11-08T17:10:37Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "0084ec74-546a-4914-8039-d3830766e163",
    name: "Tendro",
    description:
      "Tendro delivers intuitive and future-oriented software that reduces the total time and costs associated with procurement and portfolio management. Procurement processes are time- and resource-intensive for all the involved parties. Inefficient communication, lack of project overview, and little standardization makes the process expensive and cumbersome. Tendro develops software that enables more efficient contract management, verification, visual project overview as well as risk calculations.\n\nTendro gives time and resources back to professional builders and business holders – through effective tendering.",
    url: "https://www.tendro.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-eb6e919303a918b0f251ab01a77616ad5efbd7ee-720x720-png",
    createdAt: "2024-03-12T19:41:56Z",
    updatedAt: "2025-06-02T13:15:01Z",
  },
  {
    id: "023b7f6e-c6f7-4bb8-82f1-fb25f9d02f6b",
    name: "FLOKE",
    description:
      "FLOKE is a digital service designed for the smart organization of travel for small and medium-sized businesses—without the need for costly third-party providers, extra workload for employees, or a loss of focus on core activities over time.\nBy offering organization of trips from A to Z that both build culture and support strategic goals tailored to your company's needs, every trip becomes an investment with a good return.\nSMBs deserve an affordable solution that is customized to their needs and delivers real value without compromising the bottom line!",
    url: "",
    linkedin: "",
    mail: "andersson.elink@gmail.com",
    isInHouse: false,
    logo: "image-51b7af36169112e8668769dc9ae9ab697e4e6c38-500x500-png",
    createdAt: "2024-11-15T10:31:58Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "0267f4f4-c26b-45d4-9049-daac6831872c",
    name: "Dogu",
    description:
      "Dogu is a software company which develops data visualization solutions for businesses. They describe themselves as a bunch of brave nerds combining their genuine love of technology with a strong business acumen. Their flagship product is SalesScreen, which is a digital platform that uses gamification to boost motivation and increase sales revenue. Their product line also includes LiveScreen and VisitScreen, which serve to make it easy for companies to promote their services, engage with customers, and provide information to visitors. They believe that Trondheim will continue to be a world leader for technology, innovation, and entrepreneurship. Their CEO and co-founder, Sindre Haaland, graduated from NSE in 2013.",
    url: "https://salesscreen.com/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-938363e58acf75bf5e89eb705b33f72479f0158f-401x400-png",
    createdAt: "2024-03-12T22:21:08Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "048a96ef-e3c6-4234-8506-a1b880313e80",
    name: "Auge Technologies",
    description:
      "In Auge we believe that choices matter. We create a virtual world of the workplace. Professional opportunities, tasks- any employee experience available in an organization. Through exploration, employees can test different organizational opportunities, providing leaders with valuable information on engaging and developing their assets. We structure data and provide suggestions for strategic actions that can be implemented to develop employees. Keep employees engaged, and challenged, to retain their experience and skill.",
    url: "https://auge-tech.no",
    linkedin: "https://www.linkedin.com/company/auge-technologies",
    mail: "",
    isInHouse: false,
    logo: "image-8b852a98f9317fb3fca0dc83d179efa0c1bfdde4-1024x1024-png",
    createdAt: "2024-03-12T19:47:12Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "077ab0cf-b172-42c2-a831-dcc618c41d7e",
    name: "Kelpinor",
    description:
      "Kelpinor is a Norwegian marine technology company originating from NTNU. Kelpinor has developed a method for harvesting and launching kelp, enabling economies of scale.\n\nKelpinor enables alternatives to fossil fuels and traditional protein sources, by specializing in large-scale cultivation of seaweed. The company’s production facilities are located in Gildeskål municipality – the northern Norwegian epicenter for seaweed cultivation.",
    url: "https://www.kelpinor.no/",
    linkedin: "https://www.linkedin.com/company/kelpinor/",
    mail: "",
    isInHouse: false,
    logo: "image-f7896e035d374c20fdc2b0db42f2a1ad905f4c88-1024x1024-png",
    createdAt: "2024-03-12T19:48:12Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "0dd0c364-6add-4bb3-acb1-98f94d1ed6a5",
    name: "AssiStep",
    description:
      "We help people stay independent\n\nAssiTech AS develops AssiStep, the walker in the stairs, giving elderly and people with reduced mobility the security and support to climb stairs themselves. Students at NSE started working with the concept of the AssiStep based on a report from InnoMed, describing how many struggle with climbing their stairs. The first funding for the development was secured after ten months of work in october 2012, and the first prototype was finished in december 2012. After user testing several iterations of prototypes, a finished product design was prototyped in the spring of 2014. The company successfully sourced investors through an equity crowdfunding, and the product will be launched in the autumn of 2014. The company currently employs 3 people, including NSE graduates Halvor Wold and Eirik Medbø. AssiTech AS aims to expand internationally the coming years, developing and selling aids to help people stay active and independent.",
    url: "https://assistep.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-9bd6408401bd6b54e7809e5e21e2fec8125b4a9d-1024x1024-png",
    createdAt: "2024-03-12T19:55:39Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "10473f5f-c9e1-4215-9b83-ba7b0b7ab334",
    name: "Drowzee",
    description:
      "​Any form of improvement requires feedback in order to work. When you learned how to ride a bike, your eyes and balance were essential in order to get better. When practicing mental functions, we lack the same feedback sources.\n\ndrowZee is developing consumer friendly brain wave sensors, in order to provide visual and audiovisual feedback when practicing mental functions. The first milestone is to help people fall asleep in less than 5 minutes.\n\nMany physical processes are controlled by our psyche. Neurofeedback is a technique that involves metal sensors which picks up the electrical potentials coming from our brains.\n\nIt gives you a better overview of what is going on inside your own mind, and the ability to train the mental functions which you cannot train today.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-f80c10d4c8a8c3665705b359009b526bfb6506ff-720x720-png",
    createdAt: "2024-03-12T22:24:41Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "153beca6-dbc0-44cc-84a3-4aa23ce4cbcc",
    name: "Costail",
    description:
      "Costail makes electronic tails for cosplayers. It is the first tail that moves automatically and naturally with your body as you walk. Developed at the Norwegian University of Science and Technology, the tail requires no remote control, and works just as if you were an animal. Costail is bringing the 21st century to costumes.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-889871a506bce22e749de72c96647992c741e166-766x766-png",
    createdAt: "2024-03-12T20:04:29Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "1b8ce334-ffd3-47c0-b43a-bfaf2b17581e",
    name: "Combine",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-4b68425334eaabae1393ec094b001c2551537cfb-900x900-png",
    createdAt: "2024-03-12T22:40:30Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "1d6e90f6-843a-43aa-805e-65b518d1d95d",
    name: "Amok",
    description:
      "Amok Equipment is one of NSE outdoor alibis. The team behind Amok Equipment created a business out of their mutual passion for the great outdoors. Their first product is a camping hammock, Draumr. This hammock is unique in is genre and has a flat sleeping position, a pocket for your sleeping pad and can also function as a chair. It was launched in the spring of 2014, after several months of testing and developing. The company has received two rounds of funding from Innovation Norway, they have a patent pending and the hammock has already been sold to over 15 countries.\n\nJonas Haug conceived the idea sailing in the Caribbean the summer of 2012. At NSE he met Steinar Bukve Witsø and Elin Kathrine Saunes, who teamed up in January 2013. ",
    url: "https://www.amokequipment.com/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-fe721cd6b506a1c6a1a26ea40cde58b206943317-780x780-png",
    createdAt: "2024-03-12T20:02:15Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "25348334-2b70-4d7e-abe3-bcce5e32946c",
    name: "PramPack",
    description:
      "Protecting your valuables!\n\nPramPack was founded in 2008 by Anne Morkemo, Audun Ueland (ES) and Anders Mjåset (ES). Anne had flown around the world with her young son and felt the pain of travelling with a pram- it broke and ruined her vacations. Anne was not alone, and the problem was affecting millions of family travels in Northern Europe alone. She came up with a brilliant idea for a new type of special luggage for prams, which later was patented. Together with Audun and Anders she commercialized the idea and within 2011 PramPack was winning international design and industry awards around the world. Within the same year they had sales in more than 500 stores in six countries, and distributers in more than 35 countries wanted the product rights for their regions. Big airliners like Norwegian and SAS partnered up with PramPack making the product the first ever pram luggage to be “approved” by international airlines in the region. After three successful startup-years the company was sold to Stokke for an undisclosed sum and the product is now available throughout Stokkes sales network in more than 55 markets internationally.\n\nThe founding team has gone on to become serial entrepreneurs with Anders and Audun founding MESH in 2012 – Norways leading innovation platform for modern entrepreneurs, and Anne founding Ågot Lian – a seafood restaurant in Trondheim. Combined they employ more than 50 people and their companies are rapidly expanding. They are advisors to the government on entrepreneurship, members of WEF Global Shapers and Anders was Norway’s youngest delegate to the World Economic Forum in Davos 2014. They sit in various boards of startups and have also done angel investing.",
    url: "https://www.stokke.com/no-no/barnevogner/stokke-prampack/191400.html",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-5bec35113a161ff4e5511a0a6a3bdd6695bdb589-500x500-jpg",
    createdAt: "2024-03-12T22:52:19Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "25720de8-7923-48a7-943f-e89d1e3a3e98",
    name: "Agoprene",
    description:
      "Agoprene develops a greener alternative to rubber. By using algae as the main raw material source, we will reduce the material’s need for natural latex, and at best eliminate the need for natural latex completely.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-84d34e7a37bc324607fafe58c3280069b292b39d-1024x1024-png",
    createdAt: "2024-03-12T19:53:53Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "27a6895e-0666-435e-9843-9a1372e91bd3",
    name: "Naya",
    description:
      "NAYA was founded by Eirin Fossberg and Victoria Jenserud with optimism to change the world for the better. We employ and empower women from Indian slums so that they can take the step out of poverty. By providing women with technology-related training, NAYA offers human-powered labeling services for the development of image recognition to Norwegian technology businesses. NAYA connects people in the global south to work in the digital age.\nNAYA = नया = NEW",
    url: "",
    linkedin: "https://www.linkedin.com/company/nayasolutions/",
    mail: "",
    isInHouse: false,
    logo: "image-d56d9eceaac6ff988df9b3868f235e38452da13c-1024x1024-jpg",
    createdAt: "2024-03-12T19:36:27Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "2a978d9f-fe9d-4c89-ad31-36b2cb7dbb1f",
    name: "mode sensors",
    description:
      "Mode Sensors AS develops non-invasive wearable devices for medical purposes. First move is to attack the dehydration and malnutrition issues among elderly.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-8d90939ed21bec16669b218563db964240f00fc0-300x300-png",
    createdAt: "2024-03-12T22:46:25Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "2f1e2e19-958c-486a-a0bd-d64ae46703f4",
    name: "Mittalmar",
    description:
      "Mittalmar is a software company that provides the digital tools of the future to YouTubers. By applying technology, we build tools that make everyday life easier and less hectic for content creators. Mittalmar works to free up time, reduce stress, and promote better mental health among YouTubers. We combine extensive experience in content production on YouTube with expertise in programming, development, and technology to create the leading tools for content producers.",
    url: "https://mittalmar.no/",
    linkedin: "https://www.linkedin.com/company/mittalmar/?viewAsMember=true",
    mail: "",
    isInHouse: false,
    logo: "image-8755be734f434c0189be4b717290570a485377bd-800x800-png",
    createdAt: "2024-03-12T19:35:05Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "2f3f91d3-0474-415f-aff5-26cd74f17f11",
    name: "Db",
    description:
      "Better journeys through smarter travel gear\n\nThe Douchebags concept was born in the summer of 2009 during a week of sunny glacier skiing and epic surf in the beautiful western part of Norway. During that week, twin-tip legend Jon Olsson met NSE student Truls Brataas, and the two discovered a mutual passion for action-sports, traveling and smart product design. With the exclusive goal of creating better journeys through smarter travel gear, the two initiated the Douchebags project.\n\nDuring 2010 NSE student Erling Magnus Solheim joined the team, and by 2012 the small company had won several international design awards based on their PCT patented technology and succeeded as a born global.\n\nToday, the company is selling its product in more than 500 retailers in 20 countries, and is widely know as the market leader within its segment. The company is rapidly growing as it is taking on new segments redefining how people travel.",
    url: "https://dbjourney.com/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-1dd678f6aeda3790812ce766335005d9cd35c62c-1297x865-jpg",
    createdAt: "2024-03-12T22:21:41Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "30fd35b0-4053-4df6-b329-df99c99ec56f",
    name: "Hark Technologies",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-dcf189e53c5d9ccca2e3835dad451d22ecb7119d-1024x1024-png",
    createdAt: "2024-03-12T22:43:06Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "331a3b66-d89f-4c8a-aee3-000ed4968571",
    name: "Woolero",
    description:
      "Woolero develops sustainable packaging of Norwegian surplus wool. Every year, tons of Norwegian sheep wool are thrown away as a result of low demand. Due to the rough climate in Norway, the wool becomes too coarse to spin into yarn and is therefore unsuitable for clothing production. In 2020, the wool price was set to zero kroner, which makes it more profitable for Norwegian farmers to throw away or burn the wool, rather than deliver it in for money. Woolero uses the surplus wool to produce a non-woven material that can help replace plastic packaging in online shopping.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-542b0fd62cd2d748035b97c6121f0d5e23304cdf-300x300-jpg",
    createdAt: "2024-03-12T19:54:32Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "39ddb02a-45f8-457b-854c-e4ce97b408fd",
    name: "Snowroller",
    description:
      "Snowroller creates retro-inspired ski apparel to people who want to stand out on the slopes, at après-ski and in social media.\n\nThe Snowroller concept was born in April 2017 when CEO and founder Linnea Tveraaen went on a ski trip with her friends to Trysil. They were frustrated because they did not have a perfect outfit for both the slopes and après-ski. This was the beginning of Snowroller, and six months later Snowroller launched its first collection of ski suits.\n\nIn November 2018, NSE student Eva Røgler joined the Snowroller team. As of today, the team consists of NSE student and CEO Linnea Tveraaen, CMO Eva Røgler and Caroline Klund as a part-time designer.\n\nAfter two successful winter seasons, the company has sold over 1500 ski suits to the Norwegian market, and are focused on growing internationally and wider its product portfolio in the coming years.",
    url: "https://www.snowroller.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-56662f436d7bd73e4ba21a1cfe8a4db69d6b8b08-878x879-jpg",
    createdAt: "2024-03-12T22:57:56Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "3a241c1d-db7a-483e-bde4-083380ce2bfa",
    name: "Compax",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-03503ecbfd6ca5d2004a30369fe2980b0ac0c46f-1024x1024-png",
    createdAt: "2024-03-12T22:41:30Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "3df3e625-c4dc-4aa3-8500-18daacdf843c",
    name: "Capeesh",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-71dcb0803cef87e483e36b81075c69cb06829a35-1024x1024-png",
    createdAt: "2024-03-12T22:39:50Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "415da59f-a8f8-4116-881d-4fa4840e14f4",
    name: "Useless",
    description:
      "UseLess is a platform and community dedicated to selling unique, ethically produced clothing and sewing patterns. Our vision is to encourage more sustainable consumption in fashion by bringing together great alternatives to fast fashion in one place. At the same time, UseLess opens its doors to new and small-scale designers, giving them an opportunity to showcase and sell their products to a wider audience. Useless empowers change through creativity.",
    url: "https://uselesshq.com/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-3252f95ff182cc375de479b83c0a7d3613c68b4d-1024x1024-png",
    createdAt: "2024-03-12T19:37:05Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "47a12b97-3cbc-4446-8287-1e96ab3ed14c",
    name: "Rendra AS",
    description:
      "Integrated operations for the construction industry\n\nRendra AS is pioneering integrated operations in the field for the construction industry. The core of Rendra’s product, Rendra O, is a unique streaming platform that handles gigabytesized Building Information Models(BIM) and thousands of drawings with ease.\n\nBased on this technology, Rendra O has developed functionality that enable fast and effective operations, so the construction workers can focus on delivering construction projects on time and budget. Rendra O was designed in close collaboration with some of the largest industry players in Norway through several successful pilot projects, such as Helse Sør-Øst, Helsebygg Midt-Norge, Veidekke and Caverion among other. The company has recently closed their first commercial sale and is currently being used in several construction projects in Norway. Rendra was founded in 2012 by five students from NSE and has now successfully secured seed funding from Arctic Innovation Group.",
    url: "https://www.rendra.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-9900d62f5005895f3cc52bfb9dd43fb18a1671a3-300x300-jpg",
    createdAt: "2024-03-12T22:55:37Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "4a6f921e-558e-474d-8547-dcd53a4f23a5",
    name: "Wepost",
    description:
      "Wepost is an AI copilot for growth marketing teams who don’t want one campaign, but endless campaigns. Wepost saves you time by gathering all of your marketing and PR materials in one place. Find and utilize your target audience. Create marketing plans and strategies to engage your audience. It is affordable and has a fixed price, unlike a marketing agency. You don’t need a marketing person or team. Wepost gives you superpowers and can execute on your existing business strategies. We give you the knowledge you need to make the right decisions with your marketing efforts. Generate creative narratives at the right time and place without effort. Wepost makes your stories come alive!",
    url: "https://wepost.ai/",
    linkedin: "",
    mail: "benjamin@wepost.ai",
    isInHouse: false,
    logo: "image-aacacefef72af2c2f63c03a30a389c8caef6c7ce-4644x4644-png",
    createdAt: "2024-03-12T19:38:05Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "4ef37a69-0f6e-4354-95c6-356dbe668762",
    name: "BevArt",
    description:
      "Teknologiselskapet BEV/ART hjelper museer bevare kulturarven for fremtidige generasjoner. Ved hjelp av markedsledende sensorteknologi, overvåker og beskytter bedriften umistelige kunst- og museumsgjenstander.",
    url: "",
    linkedin: "https://www.linkedin.com/company/bev-art/",
    mail: "",
    isInHouse: false,
    logo: "image-8095f432eef9757b777a2cb0bec632d2387b7ae7-1024x1024-png",
    createdAt: "2024-03-12T19:48:58Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "58c80a3a-10e9-4334-921e-a230668d1536",
    name: "wiral",
    description:
      "Wiral is a motorized camera system that easily attached to a wire enables filming at a distance.\n\nCabel cam symstems have brought dynamic shots to the big screen for over a decade. The problem is that these are for high production cameras. These systems are heavy, expensive and time consuming to both install and maneuver. With the arrival of GoPro and an increasing number of amateur filming, people therefore started making these themselves, but very few holds this kind of knowledge/expertise.\n\nTrying to position us in the gap between the most expensive and best gear on one side and the diy cheap solutions on the other, we are introducing Wiral. An affordable, easy to set up cable cam for the filming purposes with both mobile and smaller cameras such as GoPro. It enables filming in challenging areas, where drones are impractical or straight out dangerous.\n\nA cabel cam system for you and your friends, to enable cool and professional looking film clips.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-56cb79669333714daf0bab56ec6ac912a4f4cbb3-300x300-jpg",
    createdAt: "2024-03-12T23:02:44Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "5c4bfa08-4b55-49a0-a92b-da0bbcc5db67",
    name: "jodacare",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-a303f0d74a583bfe30fc83ded146fb25038bbf52-900x900-png",
    createdAt: "2024-03-12T22:43:36Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "5e7d0ddc-183a-42f6-bbdb-10e2f1f14caa",
    name: "GRAPHIQ",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-47d53729d1ccc63bd1552082ae829657f0266ba8-900x900-png",
    createdAt: "2024-03-12T22:42:09Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "696d4ef3-9ecb-4bb7-a6cb-192008769943",
    name: "Trevarefabrikken",
    description:
      "Trevarefabrikken is located in the village of Henningsvær, Lofoten. This rustique old wood factory (1.500 square meters) will provide co-living, foodlab and workation facilities. The fishervillage is popular not only among climbers, surfers and travelers, but frequently used as hideaway for thoughtful painters, handcrafters and wildlife explorers. Our aim is to restore the building in three phases, starting in the summer of 2015.",
    url: "https://trevarefabrikken.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-f2584cc6e09342def9a8c4afd7050efd760b8fc4-300x200-jpg",
    createdAt: "2024-03-12T23:00:52Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "6a3d6df2-6001-4d8c-81fa-aaa6298f8ba5",
    name: "Connect LNG",
    description:
      "Enabling LNG Terminals\n\nConnect LNG will enable distribution of cleaner and cheaper energy to the world by commercializing the Universal Buoyancy System (UBS), a buoy solution for LNG transfer between ship and shore. The system enables a much faster installation time, reduces investment costs and reduces investment risk by providing mobile infrastructure compared to the alternative, which is to build a quay or jetty.\n\nThe Connect LNG founders are young people with innovative mindsets from NSE and NTNU Department of Maritime Technology combined with highly experienced people within the oil&gas and maritime industry.\n\nSince the startup in 2012, three model tests have been conducted at NTNU/MARINTEK with great success, and DNV-GL has issued a statement of feasibility for the system. The company is supported by NTNU Discovery, Innovation Norway, Partnere for Nyskaping, and the Norwegian Research Council. The company is experiencing formidable momentum, and has received a lot of international interest.",
    url: "https://www.connect-lng.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-2714f44eefb66013570e24bdad75e9ff48f5e794-640x427-jpg",
    createdAt: "2024-03-12T20:04:41Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "6cdd4118-ac23-4c15-9fe7-52de2bb9bd7b",
    name: "Leasi",
    description:
      "At Leasi we believe in a future where all construction machinery is shared through rental, reducing the footprint of the construction industry. We do this by providing construction equipment rental companies with a tool for fleet optimization, saving time, increasing revenue and allowing for scaling possibilities.",
    url: "http://www.leasi.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-e380c3dd74890707c629c89ab42af4d7897cd827-1024x1024-png",
    createdAt: "2024-03-12T19:51:40Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "6cf2b584-dc6f-4cb0-be58-16f934bb57e9",
    name: "Nibbi Clothing",
    description:
      "Nibbi Clothing is a community-driven tennis & lifestyle clothing brand – inspired by tennis’ culture, aesthetics, and history. We are also a “sports club” where customers have the opportunity to participate in tournaments, trainings and events. Our goal and vision are to spread the lifestyle associated with tennis, both off and on the court.Nibbi clothing is strongly inspired by the aesthetics and colors of tennis, with sportswear and cotton garments. The sportswear consists of full tennis sets with shorts, piques, t-shirts, socks, caps, and cushions. All the cotton garments are hand-printed by us in Oslo. This makes it possible for us to create our own prints and motives, using a technique called screen printing. We release several small collections with unique prints and colors for Nibbi, in addition to collaborations with some selected partners.We want to be a brand that inspires people to get out on the court by bringing out the playfulness, social and sporting aspects of Tennis. Tennis is a sport that suits all levels – we are a brand for both newcomers and professional players.\n\nWe mainly sell through our online store at www.nibbiclothing.no, where we always have all the products available. Throughout the year we also have several pop-ups. We use the online store to communicate with customers through stories and unique offers for our sports club members.",
    url: "https://nibbiclothing.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-dc70447a7ab9b4ee27ea39fa85382e215adaa778-1024x1024-png",
    createdAt: "2024-03-12T19:45:43Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "6d55938f-cdb5-4f12-aa8d-881140d0ff60",
    name: "ALVA",
    description:
      "The Future of Electric Motors. Alva is developing a new production method for electric motors and generators, enabling lower weight, higher efficiency and low production costs. Their patentable technology can be used for several applications, including wheel-motors, subsea generators, wind turbines and drones.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-1d785ac0edb2ce418ad88f9883d94ac885da2c04-1000x1000-png",
    createdAt: "2024-03-12T19:58:47Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "6ecb3e18-f101-49ee-8d0c-f9fd55bdb634",
    name: "Scoped Solutions",
    description:
      "Scoped Solutions develops software that give real estate companies complete control over their portfolio performance, enabling them to drive targeted and impactful building measures. Though data-driven insight and analysis, our software pinpoints where upgrades are needed and recommends effective measures. Scoped Solutions aim to streamline sustainable practices, making the real estate sector more ready to meet environmental goals.",
    url: "https://www.scoped.no/",
    linkedin: "https://no.linkedin.com/company/scoped-solutions",
    mail: "henrik@scoped.no",
    isInHouse: false,
    logo: "image-81f5278ab22e2391cb3a640ebac5ff203e3eb4e4-500x500-png",
    createdAt: "2024-11-11T14:26:04Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "713b4265-ce5b-45e0-986b-1907554f997b",
    name: "Ocean Access",
    description:
      "Transmitting large datasets from the seabed at remote locations to shore is challenging and costly. At the same time, it is vital to gather more ocean data for environmental research and better understanding of the ocean. Ocean Access is making the ocean more accessible by developing a surveillance system that is able to communicate autonomously subsea-to-surface and that is not dependent on existing subsea infrastructure. By doing this we can facilitate ocean research, help detect oil and gas leakages and assist in prognosis of harmful algae blooms for the aquaculture industry. Our company consist of the founders from NSE, Andreas Mauritzen and Fredrik Lilleøkdal, as well as a competent team of engineering and business students from NTNU.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-09ddd46414a47eaca8741cadec118b4353a98cf9-1000x1000-jpg",
    createdAt: "2024-03-12T22:50:24Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "759a62bc-b7a4-46fe-bcf8-985f9447bd5d",
    name: "TuniSea",
    description:
      "TuniSea aims to produce sustainable and nutritious food products from tunicates (Ciona Intestinalis) by cultivating them offshore. Tunicates can be grown and processed in a very climate-neutral way, as they do not require feeding, fertilization, or access to light. Tunicates are well-suited for food production since the species is rich in omega-3, protein, and amino acids, with a taste of umami. The cultivation also has the potential to be economically scalable, as the species is suitable for high-volume cultivation in a small area, while requiring minimal energy.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: true,
    logo: "image-fd7230709988739a74df095c4468c331ae15f3be-500x500-png",
    createdAt: "2024-11-11T14:27:26Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "82510094-b30d-46f6-8399-a82cbf2f5331",
    name: "EquaFish",
    description:
      "Equafish creates a decision-making tool that gathers all available data on land-based fish farms. This tool reduces uncertainty in decision-making by presenting data in a user-intuitive way to all employees through effective correlation analyses. As a result, it enhances knowledge and the decision-making foundation, reducing the risk of mass mortality and disease for the hundreds of thousands of fish swimming in each tank.",
    url: "https://www.equafish.com/",
    linkedin: "https://www.linkedin.com/company/103644847/",
    mail: "Finn@equafish.com",
    isInHouse: false,
    logo: "image-81fceb2ad12a494a708ecfbfebe44e176f05c03c-500x500-png",
    createdAt: "2024-11-08T16:06:45Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "89bcf881-c4cd-4605-8303-d3962a755423",
    name: "Seasy Data",
    description:
      "We simplify the collection and sharing of emissions data from the value chain. We’re not just facilitating compliance and reporting; we’re empowering businesses to make more informed and conscious decisions. Our mission is to reduce global climate gas emissions by providing a good basis for decision making.",
    url: "https://seasydata.com",
    linkedin: "https://www.linkedin.com/company/seasy-data/?viewAsMember=true",
    mail: "anna.leonora@seasydata.com",
    isInHouse: false,
    logo: "image-80e4ff994d8f4bcef586ec180c615dd78a6a3b85-1600x1600-png",
    createdAt: "2024-11-11T09:16:05Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "8cd4e1b7-4860-421b-91e4-65108cb87c54",
    name: "Hubro Education",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-652d9bc86ca96a4dc8f35222e816e8ae5d9c5f4f-1024x1024-png",
    createdAt: "2024-03-12T22:42:34Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "8d4db3fc-1af3-436b-92b0-413d56520cce",
    name: "Vilje Bionics",
    description:
      "Imagine how your life would have been if you could not move your arms and hands. Vilje Bionics empowers people who suffer upper motor lesion with a robotic exoskeleton, This exoskeleton allows patients to move their elbow, shoulder, wrist and hand and gain independence and a sense of mastery in their daily activities.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-aed42e299dcf7369ba6b72146e6dd35dc9c87b72-900x900-png",
    createdAt: "2024-03-12T23:02:11Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "93aef3b1-d2bc-4ec6-98fd-fbc0fe99af36",
    name: "Ragnarock Geo",
    description:
      "RagnaRock Geo develops AI software which aids oil and gas companies in exploration. The software uses machine learning to interpret subsurface data and has an intuitive interface which acts as a “smart assistant” for exploration experts. RagnaRock Geo’s mission is to make the interpretation workflow more efficient and creative so that geoscientists can focus on the value-creating tasks. We are a young and agile startup that aims to excel at using machine learning on subsurface data.",
    url: "https://www.ragnarockgeo.com",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-1fffbda22c2c8b2020d15fc001c794d21535525d-1024x1024-jpg",
    createdAt: "2024-03-12T22:54:26Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "9b65407a-adaf-495c-a3ce-c694924b9ec4",
    name: "BitPet",
    description:
      "BitPet is an Augmented Reality multiplayer mobile game inspired by Pokémon Go and Tamagotchi. In BitPet, each player takes care of digital pet by feeding and walking it, and interacting with other pets in AR. The pet’s health depends on the activity from the user’s smartphone-pedometer, motivating them to be more physically active. The game will also encourage social engagement as players can choose to meet other players’ pets, or explore the AR word together.",
    url: "https://www.bitpet.io/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-9f26c9361907d4813965397f8c638aa5fe33d978-1024x1024-png",
    createdAt: "2024-03-12T20:03:56Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "9bfa567d-297a-47e7-b4b3-426c26dd09f3",
    name: "Fornix",
    description:
      "Fornix – Better mental health, for a more sustainable worldAt Fornix, our vision is to reduce the prevalnce of anxiety disorders in socity.We offer professional therapists from the mental healthcare sector the tools to conduct exposure therapy in a pre-programmed virtual environment, where one can choose from different simulations depending on the patient’s needs. This can make therapy more accessible and more engaging. As such, we contribute to the UN’s third sustainability goal; Good Health and Wellbeing.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-02c40ba7d5b1ba6b86b0a644cdac20e0d5c6d2b0-300x300-png",
    createdAt: "2024-02-19T22:04:04Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "9f0b95cb-8a81-4402-b5e2-deddd98ae5ff",
    name: "Rocketfarm",
    description:
      "What do you do when you have just started your own company and in the search for a good time tracking service find that most time tracking systems are more complicated and difficult to use than they need to be?\n\nYou make your own of course! Provided you have access to four brilliant minds, a lot of programming hours and the idea to make time tracking as easy, and as minimum invasive to your work day as possible.\n\nToday, Yast has over 90.000 unique users worldwide, and has been acknowledged for combining end user friendliness with powerful reporting capabilities.\n\nDue to Yasts success, our company has grown and so has our field of expertise. In the growth process the name Yast was changed to Rocketfarm AS. Rocketfarm offers development- and consulting services, stretching from advanced robotics to web safety and mobile- and web apps. We continue to realise our customers wishes and develop our own ideas into valuable products.\n\nOur goal is to create, and create again.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-6aaa3baf3b77970887f93a3e29609adb0a54d15a-400x400-jpg",
    createdAt: "2024-03-12T22:53:46Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "aba260d4-4ed3-4f18-a206-5d5788465791",
    name: "Telescope",
    description:
      "(Formerly Ei Solutions)\n\nTelescope offers practical tools for managing sustainability risk in real estate. They started as Ei Solutions in 2021 at NTNU School of Entrepreneurship. NSE Alumni on the core team include Gustav Haaland and Marit Bjerkreim.",
    url: "https://www.telescope.eco/",
    linkedin:
      "https://www.linkedin.com/company/telescope-eco/posts/?feedView=all",
    mail: "gustav@telescope.eco",
    isInHouse: false,
    logo: "image-55bf05e37db72771f3499463e2b60ab2796a4230-243x156-png",
    createdAt: "2024-11-08T15:48:28Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "b1403d6d-8d0e-4315-9917-9c1077dacb7f",
    name: "DropRacks",
    description:
      "DropRacks is developing new and innovative roof racks that can be lowered on the side of your car. Our goal is to make the loading process of equipment more efficient, practical and secure (HSE). Large and heavy equipment can easily be loaded on the car by one person. In the first phase the roof rack will be adapted to the professional market, targeting carpenters, craftsmen, entrepreneurs and similar industries. The next step is to develop a roof rack adapted to the private market.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-e34ebd87007b8990c654be4478723b2cc10a8f3f-300x300-jpg",
    createdAt: "2024-03-12T22:27:49Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "bd1d8687-ee78-4c43-a5fe-f5f8c0643e1b",
    name: "OmniMod",
    description:
      "OmniMod aims to transform the processing of parcels and goods in E-commerce logistics, intralogistics and distribution through automation. Our vision is to enable increased value-creation, for businesses of any size, through digitalization and abstraction of logistics. The technology makes up a system that can be configured and used for multiple purposes within the mentioned markets, including sorting of parcels, sequencing of parcels, Micro fulfillment centers, and automated storage and retrieval.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-42844ab605574492715223a20f4a775ce979cdd3-300x300-png",
    createdAt: "2024-03-12T20:01:00Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "bdff0ba4-2590-45be-b032-53854af91634",
    name: "Tone",
    description:
      "People with dementia benefit greatly from listening to the right music. Tone aims to make the right music accessible through a customized interface designed for people with dementia and their loved ones. Specifically, it includes preference-mapping software and a speaker with just one button.",
    url: "",
    linkedin: "https://www.linkedin.com/company/tonenorway/",
    mail: "guttohn@gmail.com",
    isInHouse: false,
    logo: "image-05f5497c9958c4c6ce34f3b32beee6d26f4d398d-500x500-png",
    createdAt: "2024-11-14T19:49:38Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "bf71361d-c9b4-4bd5-86f8-4458e6a5218d",
    name: "Skypass",
    description:
      "Skypass is developing a cloud-based platform for internet retailers with high return rates. In fashon e-commerce, up to 50% of all items gets returned by the customers, thereby creating a big revenue loss in the industry. The Skypass solution collects data from the different stages of the transportation process, and auto-generates customs refund applications. This provides retailers with the necessary documentation to get a full customs refund on every return. The Skypass solution can generate customs refunds equivalent to 3-6 % of turnover in Norway for fashion retailers. Our goal is to make data more accessible for retailers, thereby allowing them to pay the correct amount of customs on all shipments.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-e653fdacf4b895bbb196597c51a449bc5596086c-1024x1024-jpg",
    createdAt: "2024-03-12T22:56:59Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "c7921e69-50c1-44b6-852d-ddcfb88735d3",
    name: "Arealize",
    description:
      "Whenever a property becomes vacant, commercial real estate companies send floor plans to potential tenants (companies), customized to each company based on a series of parameters.Today, this is done by technical personnel in a manual, slow, and expensive process, due to the large amount of data sources and parameters that need to be considered. Arealize is working on automating this process and provide innovative commercial real estate companies with an AI-driven generative design solution for quickly drawing up early-stage floor plans, cutting this process from weeks to just a few hours.",
    url: "https://arealize.ai/",
    linkedin: "",
    mail: "contact@arealize.ai",
    isInHouse: false,
    logo: "image-2b047983eb61f5cb7cadb02e0c381b76a5ed3ac2-300x300-jpg",
    createdAt: "2024-03-12T19:59:37Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "cb09f296-7120-4ad3-850c-51f825f63bbd",
    name: "Ei Solutions",
    description:
      "Ei Solutions is a technology company dedicated to enabling the green transformation of the real estate industry.\nOur analysis engine generates the sustainability insights the industry needs to comply with the EU-taxonomy’s screening requirements with just a click. This provides an overview of potential red flags instantly for real estate owners in order to target the sustainability issues that really matters in the portfolio.",
    url: "https://www.eisolutions.no",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-56652b11526248253c55f52bc29d60a648edad1f-1024x1024-png",
    createdAt: "2024-03-12T19:44:00Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "d084e350-bf67-47a7-a389-6d3a334af2b5",
    name: "Enernite",
    description:
      "Enernite is a technology company founded on the belief that data insights and digital solutions could accelerate the renewable energy revolution. Gathering the required information for selecting new sites for renewable energy projects stands out as a complicated process and a bottleneck for new initiatives. Enernite utilizes advanced analysis of satellite imagery and automated information gathering from fragmented sources to enable rapid, data-driven decisions. With in-depth information and updated data of various geographical locations, Enernite’s software enables better overview and automated on-demand site assessments of selected environmental, financial, and technical factors, such as grid-network, existing infrastructure, ecology and restricted areas, and more.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-c8cd13d8b4fae3e2cf6ccab22538dcbb543e03ff-300x300-png",
    createdAt: "2024-03-12T20:00:29Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "dadb6bf0-96bc-494e-897a-a1583ec94da8",
    name: "Tind Technologies",
    description:
      "Our team collaborates with CERN (European Organization for Nuclear Research) to commercialize Invenio – an open source digital repository software. TIND Technologies is a born global startup, dedicated to provide Invenio integration, customization and hosting to organizations and research institutes all over the world. We help preserving the world’s intellectual and scientific capital.",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-1bac83bb93dfa1a8727c9443a10d5d89118397f4-800x800-png",
    createdAt: "2024-03-12T23:01:23Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "dafac9d8-8f1e-4a9c-9550-1d060cd8c6fa",
    name: "menomed",
    description:
      "Menomed is a digital platform for women going through menopause, offering information, guidance, and treatment to support female employees in the workplace. Through video consultations with gynecologists and tailored corporate solutions, Menomed helps reduce sick leave, enhance quality of life, and improve job satisfaction. The goal is to break down the taboos surrounding menopause and enable women to be fully engaged and productive in their professional lives.",
    url: "",
    linkedin: "",
    mail: "renatetho0@hotmail.com",
    isInHouse: false,
    logo: "image-95e478057a0ec1e953280d4e1c88747dd1481e4f-500x500-png",
    createdAt: "2024-11-11T09:27:18Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "ddb66fb1-c898-4f07-8544-2eaf73d72545",
    name: "Hera Solutions",
    description:
      "Hera Solutions is a technology company dedicated to the vision that truck drivers should focus on driving trucks, and that cumbersome paperwork and processes can be things of the past. Hera develops a user-friendly, simple, and efficient system for handling waybills. The waybill comes directly into the app and is directly shared from the supplier to the carrier and recipient. We do this in close collaboration with the transport industry and the drivers\nthat will be using Hera.",
    url: "",
    linkedin: "https://www.linkedin.com/company/herasolutionss/",
    mail: "ingerlovise@herasolutions.no",
    isInHouse: false,
    logo: "image-61c0cd5233790a650daed86b550d8cf0a3445a5d-1024x1024-png",
    createdAt: "2024-03-12T19:53:18Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "e40544f0-5275-43f5-98ed-ebf0bab6b7ae",
    name: "Demp",
    description:
      "Demp develops innovative wall sound panels made from mycelium composite—a natural biomaterial with excellent sound-absorbing properties. By using resources like wood waste, Demp creates eco-friendly solutions to enhance room acoustics while reducing waste. Our vision is to create solutions that improve indoor environments, reduce noise, and give spaces a modern touch.",
    url: "https://www.demp-bio.com/",
    linkedin: "https://www.linkedin.com/company/dempbio/",
    mail: "helle@demp-bio.com",
    isInHouse: false,
    logo: "image-e3cccf2078cc21be300eace936bf3a5b5afa1e0e-1244x1128-png",
    createdAt: "2024-11-08T15:54:42Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "e84d7072-cf8e-4a72-b1bb-af21ff293b7a",
    name: "Hydroflow",
    description:
      "Hydroflow Technologies provides off-grid, temporary hydropower solutions to supply clean energy directly to infrastructure projects. They address the challenge of high energy costs and carbon emissions typically associated with diesel usage on remote sites. By delivering power through an independent system, including energy storage in battery containers, they offer a cost-effective, sustainable alternative that enhances project competitiveness and minimizes environmental impact.",
    url: "",
    linkedin: "https://www.linkedin.com/company/hydroflow/",
    mail: "john.brembu@gmail.com",
    isInHouse: false,
    logo: "image-7c77c0bc26b1c1b735b69f6cf1823ee95e353fb4-500x500-png",
    createdAt: "2024-11-11T10:24:01Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "e95815e2-ee02-4055-ae27-8f7790cc1226",
    name: "nLink AS",
    description:
      "Revolutionizing the construction industry\n\nnLink develops innovative mobile robot systems. Together with its sister company Rocketarm AS, the companies were founded by two NSE graduates together with three graduates from NTNU Technical Cybernetics.\n\nThe construction industry is full of hard manual work, and the worst of them all is concrete ceiling drilling. Imagine drilling the 250.000 holes necessary in a modern shopping mall, manually. This challenge was identified by Vintervoll AS, who contacted NSE and nLink. Together they are now developing the worlds first ceiling drilling robot of its kind, ready for market Q1 2015.\n\nnLink have developed the robot together with its partner and Innovation Norway. This led to a successful prototype test late june 2014. Focus areas for 2014 are hardware and software development, vision systems, apps, and a patent application soon to be filed!",
    url: "https://nlink.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-615fe4117905db37408993e3f7e6cf24d66024ea-400x400-jpg",
    createdAt: "2024-03-12T22:48:09Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "f0ae78de-829b-4862-9d83-02f8b650db2a",
    name: "Ludenso",
    description: "",
    url: "",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-0551d5d5948ac226af2a5007db90461623e4342e-1024x1024-png",
    createdAt: "2024-03-12T22:43:39Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "f1e2af59-60ff-491f-8086-90b47f833bc5",
    name: "Enve",
    description:
      "ENVE is a SaaS company disrupting the asset management industry by automating financial and operational reporting, as well as streamlining the information flow. This ensures that the correct stakeholder receives vital information about the given investment on time.",
    url: "https://enve.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-63a31aa2967ee9e31ddc97d0efea29670d6354e4-300x300-jpg",
    createdAt: "2024-03-12T22:29:11Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "f3d9fec6-0cf8-4111-9f78-0b7fb774eb2a",
    name: "Kvist",
    description:
      "Kvist delivers efficient management software for environmental certification, in construction projects. They ensure oversight, communication and risk management in all projects, through their project management system. Kvist systems are currently adapted to BREEAM and CEEQUAL, with more standards on the way.",
    url: "",
    linkedin: "",
    mail: "kontakt@kvst.no",
    isInHouse: false,
    logo: "image-2d15bf74a97eae4af2de6ac04f56d0c68353ae14-900x900-png",
    createdAt: "2024-03-12T19:55:33Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "f9acb603-db15-4461-bcbf-f63fd1c67dbe",
    name: "SlideDrain",
    description:
      "SlideDrain develops floor drains for bathrooms. Our drains have a patented solution that allows the installation process to be easier and more efficient.\nBy developing our drains to be as user-friendly as possible, we aim to significantly reduce the number of water leakages due to incorrectly installed drains.\nThat’s why we say that SlideDrain is easier, quicker and safer.",
    url: "https://www.slidedrain.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-3a2c8e7107661c8cd1b04d0b68e357d47b3176df-1024x1024-png",
    createdAt: "2024-03-12T22:59:48Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
  {
    id: "ff04e705-1f2c-404b-9d38-024c5b757c64",
    name: "Dirtybit AS",
    description:
      "Dirtybit was founded in 2011 by the two students Erlend Haugsdal and Nicolaj Broby Petersen, based on the idea to create mobile games that worked seamlessly on multiple platforms. The game Fun Run enables people to race together online in real-time, and with Fun Run they established a new market for multiplayer games in the mobile space. By June 2014 more than 40 million people have downloaded Fun Run and Dirtybit has established itself as one of Norway’s most promising mobile start-ups. Fun Run was released in September 2012 and reached #1 in the US Apple App Store in December 2012. Their newest game Dino Dash was launched in June 2014. Dirtybit consists of nine employees headquartered in Bergen, Norway.",
    url: "https://dirtybit.no/",
    linkedin: "",
    mail: "",
    isInHouse: false,
    logo: "image-602b7beda9b295fb4df39dab481940312ca77425-150x150-png",
    createdAt: "2024-03-12T22:26:17Z",
    updatedAt: "2025-02-23T13:31:08Z",
  },
];

export const STARTUPS_COUNT = 67;
